kind: environment
environment_name: dummy_sleep
state: inactive
owner_email: ronen.a@quali.com
collaborators:
  collaborators_emails:
    - dummy@acme.com
blueprint:
  name: Update sleep
  repository_name: MyBlueprintRepo
  commit: d2abfc6a60e92e245c4ac545f87a9e11f9fb65ce
inputs:
  agent: local
tags: {}
grains:
  dummy_sleep:
    source:
      commit: 237dde5bccdb268730315c58328ee49c3984971c
