kind: environment
environment_name: dummy_sleep
state: active
owner_email: ronen.a@quali.com
blueprint:
  name: Update sleep
  repository_name: MyBlueprintRepo
  commit: d2abfc6a60e92e245c4ac545f87a9e11f9fb65ce
inputs:
  agent: local
tags: {}
grains:
  dummy_sleep:
    source:
      commit: d2abfc6a60e92e245c4ac545f87a9e11f9fb65ce
