kind: environment
environment_name: dummy_sleep1
state: active
spaces: {}
owner_email: ronen.a@quali.com
blueprint:
  name: Update sleep
  repository_name: MyBlueprintRepo
  commit: d2abfc6a60e92e245c4ac545f87a9e11f9fb65ce
inputs:
  agent: qualidev-aks-forlocal-ronena
tags: {}
grains:
  dummy_sleep:
    source:
      commit: 96fcd61db57516046bfbb24308cb571c55701b1a



