kind: environment
environment_name: bpforeac-1
state: inactive
owner_email: ronen.a@quali.com
blueprint:
  name: bpforeac
  repository_name: qtorque
tags: {}
grains:
  shell-echo:
    source:
      commit: 5cce1cd96334ea9c172526b50d253ac981aa26a0
