kind: environment
description: "Example description"
source:
  blueprint_name: "example_blueprint"
  repository_name: "example_repository"
  branch: "main"
  commit: "abcdef123456"
inputs:
  input1: "value1"
  input2: "value2"
owner_email: example@example.com
collaborators:
  collaborators_emails:
    - collaborator1@example.com
    - collaborator2@example.com
  all_space_members: true

