kind: environment
environment_name: shell-echo-20231203T17555138
state: active
owner_email: ronen.a@quali.com
collaborators:
  collaborators_emails:
    - 	ronen-A@qualisystems.com
blueprint:
  name: shell-echo
  repository_name: MyBlueprintRepo
  commit: 5cce1cd96334ea9c172526b50d253ac981aa26a0
inputs:
  agent_name: qualidev-aks-colonydev-prod-ronena
  generic_input: nothing
tags: {}
grains: {}
