# Deploys AWS input source server as a clusterIp service at http://aws-input-source-service.aws-input-source.svc.cluster.local/

apiVersion: v1
kind: Namespace
metadata:
  name: aws-input-source
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-input-source-sa
  namespace: aws-input-source
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::046086677675:role/eks-assume-role # For playground-eks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-input-source-deployment
  namespace: aws-input-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-input
  template:
    metadata:
      labels:
        app: aws-input
    spec:
      serviceAccountName: aws-input-source-sa
      containers:
      - name: aws-input-source-container
        image: quali/aws-input-source-server
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aws-input-source-service
  namespace: aws-input-source
spec:
  type: ClusterIP
  selector:
    app: aws-input
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
